// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityDataPlatform.Data;

#nullable disable

namespace UniversityDataPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423215708_AddDescriptionToDataset")]
    partial class AddDescriptionToDataset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstancesCount")
                        .HasColumnType("int");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploaderUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UploaderUserId");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("UniversityDataPlatform.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mühendislik Fakültesi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tıp Fakültesi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Safranbolu Mimarlık Fakültesi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İlahiyat Fakültesi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Edebiyat Fakültesi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fen Fakültesi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "İşletme Fakültesi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Orman Fakültesi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Safranbolu Turizm Fakültesi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Safranbolu Güzel Sanatlar ve Tasarım Fakültesi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Safranbolu İletişim Fakültesi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sağlık Bilimleri Fakültesi"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Teknoloji Fakültesi"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Hasan Doğan Spor Bilimleri Fakültesi"
                        });
                });

            modelBuilder.Entity("UniversityDataPlatform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "samet@karabuk.edu.tr",
                            FacultyId = 1,
                            FullName = "Samet Sağır",
                            Password = "123",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Dataset", b =>
                {
                    b.HasOne("UniversityDataPlatform.Models.Faculty", "Faculty")
                        .WithMany("Datasets")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityDataPlatform.Models.User", "UploaderUser")
                        .WithMany()
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("UploaderUser");
                });

            modelBuilder.Entity("UniversityDataPlatform.Models.User", b =>
                {
                    b.HasOne("UniversityDataPlatform.Models.Faculty", "Faculty")
                        .WithMany("Users")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("UniversityDataPlatform.Models.Faculty", b =>
                {
                    b.Navigation("Datasets");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
